using System.Text;
using System.Text.Json;

namespace NNtrain.Audio;

/// <summary>Independent C# CPU reference for Nemotron 3.5 FastConformer/RNNT.
/// Weights remain Half; no external inference service is used.</summary>
public sealed partial class NemotronAsrModel : ILocalAsrModel
{
    private AsrArcLinear? _arc;
    private readonly AsrHalfCheckpoint _checkpoint;
    private readonly string[] _tokens;
    private readonly HashSet<int> _specialTokens;
    internal int HiddenSize { get; }
    internal int Layers { get; }
    internal int Heads { get; }
    internal int ConvChannels { get; }
    internal int Kernel { get; }
    internal int DecoderSize { get; }
    internal int DecoderLayers { get; }
    internal int VocabularySize { get; }
    internal int Blank { get; }
    internal int PromptCount { get; }
    internal int LeftContext { get; }
    internal int SymbolsPerFrame { get; }
    public long HostWeightBytes => _checkpoint.WeightBytes;
    public string ExecutionDevice => _arc is null ? "CPU (FP16 weights / FP32 arithmetic)" : $"Arc dense projections: {_arc.DeviceName}; CPU frontend, convolution and cache";
    public long PeakDeviceBufferBytes => _arc?.PeakDeviceBufferBytes ?? 0;
    public long ResidentDeviceBytes => _arc?.ResidentDeviceBytes ?? 0;
    public void EnableArc(int deviceIndex, CancellationToken ct = default)
        => EnableArc(deviceIndex, ct, null);

    internal void EnableArc(int deviceIndex, CancellationToken ct, Action<string, double>? loadingObserver)
    {
        if (_arc is not null) throw new InvalidOperationException("Arc already enabled.");
        _arc = new(_checkpoint.Weights, deviceIndex, ct, loadingObserver);
    }
    public void Dispose() { _arc?.Dispose(); _arc = null; }

    private NemotronAsrModel(AsrHalfCheckpoint checkpoint, JsonElement config, JsonElement tokenizer)
    {
        _checkpoint = checkpoint;
        var encoder = config.GetProperty("encoder_config");
        HiddenSize = encoder.GetProperty("hidden_size").GetInt32();
        Layers = encoder.GetProperty("num_hidden_layers").GetInt32();
        Heads = encoder.GetProperty("num_attention_heads").GetInt32();
        ConvChannels = encoder.GetProperty("subsampling_conv_channels").GetInt32();
        Kernel = encoder.GetProperty("conv_kernel_size").GetInt32();
        LeftContext = encoder.GetProperty("sliding_window").GetInt32() - 1;
        DecoderSize = config.GetProperty("decoder_hidden_size").GetInt32();
        DecoderLayers = config.GetProperty("num_decoder_layers").GetInt32();
        VocabularySize = config.GetProperty("vocab_size").GetInt32();
        Blank = config.GetProperty("blank_token_id").GetInt32();
        PromptCount = config.GetProperty("num_prompts").GetInt32();
        SymbolsPerFrame = config.GetProperty("max_symbols_per_step").GetInt32();
        if (HiddenSize <= 0 || HiddenSize % Heads != 0 || Layers is < 1 or > 128 || DecoderLayers is < 1 or > 8
            || encoder.GetProperty("subsampling_factor").GetInt32() != 8
            || encoder.GetProperty("subsampling_conv_kernel_size").GetInt32() != 3
            || encoder.GetProperty("subsampling_conv_stride").GetInt32() != 2
            || encoder.GetProperty("num_mel_bins").GetInt32() != NemotronMel.Bands
            || encoder.GetProperty("num_key_value_heads").GetInt32() != Heads)
            throw new InvalidDataException("Unsupported Nemotron encoder configuration.");
        _tokens = new string[VocabularySize];
        var vocabulary = tokenizer.GetProperty("model").GetProperty("vocab");
        if (vocabulary.ValueKind == JsonValueKind.Object)
        {
            foreach (var entry in vocabulary.EnumerateObject())
            {
                int id = entry.Value.GetInt32();
                if ((uint)id >= _tokens.Length) throw new InvalidDataException("Tokenizer ID outside vocabulary.");
                _tokens[id] = entry.Name;
            }
        }
        else if (vocabulary.ValueKind == JsonValueKind.Array)
        {
            int tokenId = 0;
            foreach (var entry in vocabulary.EnumerateArray()) _tokens[tokenId++] = entry[0].GetString()!;
        }
        else throw new InvalidDataException("Expected BPE or Unigram tokenizer vocabulary.");
        _specialTokens = [];
        foreach (var added in tokenizer.GetProperty("added_tokens").EnumerateArray())
        {
            int id = added.GetProperty("id").GetInt32();
            if ((uint)id >= _tokens.Length)
            {
                // The published tokenizer adds <blank> at 13088 although the RNNT
                // checkpoint has 13088 logits and config.blank_token_id=13087.
                // Extra tokenizer-only control tokens cannot be generated by the head.
                if (id >= 0 && added.GetProperty("special").GetBoolean()) continue;
                throw new InvalidDataException("Tokenizer ID outside vocabulary.");
            }
            _tokens[id] = added.GetProperty("content").GetString()!;
            if (added.GetProperty("special").GetBoolean()) _specialTokens.Add(id);
        }
        if (_tokens.Any(x => x is null)) throw new InvalidDataException("Incomplete ASR tokenizer.");
        _specialTokens.Add(Blank);
    }

    public static NemotronAsrModel Load(string directory, CancellationToken ct = default)
        => Load(directory, ct, null);

    internal static NemotronAsrModel Load(string directory, CancellationToken ct, Action<string, double>? timingObserver)
    {
        ct.ThrowIfCancellationRequested();
        long started = System.Diagnostics.Stopwatch.GetTimestamp();
        using var config = JsonDocument.Parse(File.ReadAllText(Path.Combine(directory, "config.json")));
        if (config.RootElement.GetProperty("model_type").GetString() != "nemotron3_5_asr")
            throw new InvalidDataException("Expected Nemotron 3.5 ASR checkpoint.");
        timingObserver?.Invoke("config", System.Diagnostics.Stopwatch.GetElapsedTime(started).TotalMilliseconds);
        started = System.Diagnostics.Stopwatch.GetTimestamp();
        using var tokenizer = JsonDocument.Parse(File.ReadAllText(Path.Combine(directory, "tokenizer.json")));
        timingObserver?.Invoke("tokenizer", System.Diagnostics.Stopwatch.GetElapsedTime(started).TotalMilliseconds);
        var checkpoint = AsrHalfCheckpoint.Load(Path.Combine(directory, "model.safetensors"), 2L * 1024 * 1024 * 1024, ct, timingObserver);
        started = System.Diagnostics.Stopwatch.GetTimestamp();
        var model = new NemotronAsrModel(checkpoint, config.RootElement, tokenizer.RootElement);
        ct.ThrowIfCancellationRequested();
        timingObserver?.Invoke("initialization", System.Diagnostics.Stopwatch.GetElapsedTime(started).TotalMilliseconds);
        return model;
    }

    internal AsrHalfCheckpoint.Weight Weight(string name)
        => _checkpoint.Weights.TryGetValue(name, out var weight) ? weight : throw new InvalidDataException($"Missing ASR weight: {name}");
    internal AsrHalfCheckpoint.Weight? Bias(string name) => _checkpoint.Weights.GetValueOrDefault(name + ".bias");
    internal float[] Linear(float[] input, string name) => _arc is null
        ? AsrCpuMath.Linear(input, Weight(name + ".weight"), Bias(name)) : _arc.Linear([input], name)[0];
    internal float[] Norm(float[] input, string name) => AsrCpuMath.LayerNorm(input, Weight(name + ".weight"), Weight(name + ".bias"));
    internal float[][] Linear(float[][] input, string name, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        if (_arc is not null) return _arc.Linear(input, name);
        var result = new float[input.Length][];
        for (int i = 0; i < input.Length; i++) { ct.ThrowIfCancellationRequested(); result[i] = Linear(input[i], name); }
        return result;
    }

    internal float[] Lstm(float[] input, float[] hidden, float[] cell, int layer)
    {
        if (_arc is null) return AsrCpuMath.Lstm(input, hidden, cell,
            Weight($"decoder.lstm.weight_ih_l{layer}"), Weight($"decoder.lstm.weight_hh_l{layer}"),
            Weight($"decoder.lstm.bias_ih_l{layer}"), Weight($"decoder.lstm.bias_hh_l{layer}"));
        // PyTorch names its LSTM matrices without the usual .weight suffix.
        float[] gates = _arc.LinearLstm(input, $"decoder.lstm.weight_ih_l{layer}", $"decoder.lstm.bias_ih_l{layer}");
        AsrCpuMath.Add(gates, _arc.LinearLstm(hidden, $"decoder.lstm.weight_hh_l{layer}", $"decoder.lstm.bias_hh_l{layer}"));
        int size = hidden.Length;
        for (int i = 0; i < size; i++)
        {
            cell[i] = AsrCpuMath.Sigmoid(gates[size + i]) * cell[i] + AsrCpuMath.Sigmoid(gates[i]) * MathF.Tanh(gates[2 * size + i]);
            hidden[i] = AsrCpuMath.Sigmoid(gates[3 * size + i]) * MathF.Tanh(cell[i]);
        }
        return (float[])hidden.Clone();
    }

    internal string Decode(IEnumerable<int> ids)
    {
        var text = new StringBuilder();
        var bytes = new List<byte>();
        void FlushBytes() { if (bytes.Count > 0) { text.Append(Encoding.UTF8.GetString(bytes.ToArray())); bytes.Clear(); } }
        foreach (int id in ids)
        {
            if (_specialTokens.Contains(id)) continue;
            string piece = _tokens[id];
            if (piece.Length == 6 && piece.StartsWith("<0x", StringComparison.Ordinal) && piece.EndsWith('>')
                && byte.TryParse(piece.AsSpan(3, 2), System.Globalization.NumberStyles.HexNumber, null, out byte value)) bytes.Add(value);
            else { FlushBytes(); text.Append(piece.Replace('▁', ' ')); }
        }
        FlushBytes();
        return text.ToString().TrimStart();
    }

    ILocalAsrStream ILocalAsrModel.CreateStream() => CreateStream();
    public NemotronAsrStream CreateStream(int japanesePromptId = 10, int lookahead = 3)
        => new(this, japanesePromptId, lookahead);
}

/// <summary>One utterance owns its convolution, attention, frontend and decoder caches; do not share between users.</summary>
public sealed class NemotronAsrStream : ILocalAsrStream
{
    private readonly NemotronAsrModel _model;
    private readonly NemotronMel _frontend = new();
    private readonly List<float[]> _pendingMel = [];
    private readonly List<int> _tokens = [];
    internal readonly Dictionary<string, float[][]> ConvCache = [];
    internal readonly Dictionary<int, (float[][] Key, float[][] Value)> AttentionCache = [];
    internal readonly Dictionary<int, Dictionary<int, float[]>> RelativePositionCache = [];
    private readonly float[][] _hidden, _cell;
    private float[]? _prediction;
    private bool _first = true, _final, _faulted;
    private int _lastToken;
    internal long EncoderFrames;
    internal int Lookahead { get; }
    internal int PromptId { get; }
    public string Text => _model.Decode(_tokens);
    public long DecoderEvaluations { get; private set; }
    public long DecodedEncoderFrames { get; private set; }
    public long CacheBytes => ConvCache.Values.Sum(rows => rows.Sum(row => row.LongLength * 4))
        + AttentionCache.Values.Sum(pair => pair.Key.Concat(pair.Value).Sum(row => row.LongLength * 4))
        + RelativePositionCache.Values.Sum(positions => positions.Values.Sum(row => row.LongLength * 4))
        + _hidden.Concat(_cell).Sum(row => row.LongLength * 4) + (_prediction?.LongLength ?? 0) * 4
        + _frontend.BufferedBytes + _pendingMel.Sum(row => row.LongLength * 4);

    internal NemotronAsrStream(NemotronAsrModel model, int promptId, int lookahead)
    {
        if ((uint)promptId >= model.PromptCount || lookahead is not (0 or 3 or 6 or 13)) throw new ArgumentOutOfRangeException();
        (_model, PromptId, Lookahead, _lastToken) = (model, promptId, lookahead, model.Blank);
        _hidden = Enumerable.Range(0, model.DecoderLayers).Select(_ => new float[model.DecoderSize]).ToArray();
        _cell = Enumerable.Range(0, model.DecoderLayers).Select(_ => new float[model.DecoderSize]).ToArray();
    }

    public string Append(ReadOnlySpan<float> samples, bool final = false, Action<string>? partial = null, CancellationToken ct = default)
    {
        if (_final || _faulted) throw new InvalidOperationException("Utterance is closed. Create a fresh stream.");
        try
        {
            _pendingMel.AddRange(_frontend.Append(samples, final, ct));
            while (_pendingMel.Count > 0)
            {
                int required = _first ? 1 + 8 * Lookahead : 8 * (Lookahead + 1);
                if (_pendingMel.Count < required && !final) break;
                int valid = Math.Min(required, _pendingMel.Count);
                var chunk = new float[required][];
                for (int i = 0; i < required; i++) chunk[i] = i < valid ? _pendingMel[i] : new float[NemotronMel.Bands];
                _pendingMel.RemoveRange(0, valid);
                float[][] encoded = _model.Encode(chunk, this, ct);
                // The official cache-aware generator consumes every frame of the padded final chunk.
                // Its audio-feature call has no padding mask; truncating here can lose the final token.
                DecodeFrames(encoded, ct);
                _first = false;
                partial?.Invoke(Text);
            }
            _final = final;
            return Text;
        }
        catch { _faulted = true; throw; }
    }

    private void DecodeFrames(float[][] frames, CancellationToken ct)
    {
        var prompts = frames.Select(frame =>
        {
            var prompt = new float[_model.HiddenSize + _model.PromptCount];
            frame.CopyTo(prompt, 0); prompt[_model.HiddenSize + PromptId] = 1;
            return prompt;
        }).ToArray();
        float[][] conditioned = _model.Linear(prompts, "prompt_projector.linear_1", ct);
        foreach (float[] row in conditioned) AsrCpuMath.Relu(row);
        conditioned = _model.Linear(conditioned, "prompt_projector.linear_2", ct);
        float[][] encoded = _model.Linear(conditioned, "encoder_projector", ct);
        foreach (float[] row in encoded) DecodeEncoderFrame(row, ct);
    }

    private void DecodeEncoderFrame(float[] encoder, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();
        DecodedEncoderFrames++;
        for (int step = 0; step < _model.SymbolsPerFrame; step++)
        {
            ct.ThrowIfCancellationRequested();
            if (_prediction is null || _lastToken != _model.Blank)
            {
                DecoderEvaluations++;
                var embedding = _model.Weight("decoder.embedding.weight");
                var input = new float[_model.DecoderSize];
                for (int i = 0; i < input.Length; i++) input[i] = (float)embedding.Values[_lastToken * input.Length + i];
                for (int layer = 0; layer < _hidden.Length; layer++)
                    input = _model.Lstm(input, _hidden[layer], _cell[layer], layer);
                _prediction = _model.Linear(input, "decoder.decoder_projector");
            }
            var joint = (float[])encoder.Clone();
            AsrCpuMath.Add(joint, _prediction); AsrCpuMath.Relu(joint);
            float[] logits = _model.Linear(joint, "joint.head");
            int token = 0;
            for (int i = 1; i < logits.Length; i++) if (logits[i] > logits[token]) token = i;
            _lastToken = token;
            if (token == _model.Blank) break;
            _tokens.Add(token);
        }
    }
}
