<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NNtrainArchitectureLayer>Training</NNtrainArchitectureLayer>
    <NNtrainAllowedProjectReferences>NNtrain.Core;NNtrain.Runtime</NNtrainAllowedProjectReferences>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NNtrain.Core\NNtrain.Core.csproj" />
    <ProjectReference Include="..\NNtrain.Runtime\NNtrain.Runtime.csproj" />
  </ItemGroup>

</Project>
